# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install build tools and dependencies
RUN apk add --no-cache python3 make g++

# Copy package files and config
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
COPY bin ./bin

# Install dependencies and build
RUN npm ci && npm run build

# Set execution permissions
RUN chmod +x bin/stdio

# Start command uses stdio transport
ENTRYPOINT ["node", "dist/stdio.js"]
